apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: fruits-app
spec:
  template:
    spec:
      containerConcurrency: 1
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/quarkus-springboot-demo/fruits-app@sha256:60cda46067720f6d036ce2f772d96222461a1ecfc095176e3a614482bc3421cd
        imagePullPolicy: Always
        name: user-container
      serviceAccountName: fruits-app-sa
