apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../base

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: maven-settings
    behavior: create
    files:
      - settings.xml

resources:
  - nexus.yaml
  - pvcs.yaml
  - ksvc-deploy.yaml
  - image-updater.yaml
  - fruits-app-github-triggerbindings.yaml
  - fruits-app-trigger-template.yaml
  - fruits-app-github-webhook.yaml
  - route-fruits-app-github-webhook.yaml
