apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  repositories: |
    - url: https://github.com/kameshsampath/quarkus-springboot-demo
    - url: https://github.com/kameshsampath/quarkus-springboot-demo-gitops
